# Permalinks
permalink:        pretty

# Setup
title:            Hsu Han Ooi
tagline:          Entrepreneur, Programmer, Mobile Suit Gundam Pilot
url:              http://blog.hsuhanooi.com
paginate:         1
baseurl:          /
author:
  name:           Hsu Han Ooi
  url:            https://twitter.com/hsuhanooi
  email:          hsuhanooi@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/hsuhanooi/hsuhanooi
highlighter:      rouge
navigation:
  - title: Writing
    url: /
  - title: About
    url: /about/
  - title: LinkedIn
    url: https://www.linkedin.com/in/hsuhanooi
  - title: Twitter
    url: https://twitter.com/hsuhanooi

