# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hsu Han's Software Engineering Blog
tagline:          If it ain't broke, don't fix it.
url:              http://blog.hsuhanooi.com
paginate:         1
baseurl:          /
author:
  name:           Hsu Han Ooi
  url:            https://twitter.com/hsuhanooi
  email:          hsuhanooi@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/hsuhanooi/hsuhanooi
markdown:         redcarpet
highlighter:      pygments